feidain:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.115.213.253
#    host: localhost
    port: 3306
    database: feidianexamdb
    username: root
    password: feidian52.com
  redis:
    host: localhost
    port: 6379
    database: 1

